### ISSUE TITLE
Palette of BitmapSubtitle

### ISSUE THREAD

**Issue by mozbugbox** [PyAV-Org/PyAV#177]
run `example/save_subtitles.py` error 

```
AttributeError: 'av.subtitles.subtitle.BitmapSubtitle' object has no attribute 'pict_buffers'
```

**Comment by mozbugbox** [comment]
after change `pict_buffers` to `planes`, the saved png's are all black with no text in them.

**Comment by mikeboers** [comment]
After bringing that into Photoshop and doing a levels call:

![d96b7ac0-3d46-11e6-91dd-c14c984ff839-levels](https://cloud.githubusercontent.com/assets/130470/16427810/2c795fd4-3d3d-11e6-8161-45341d96b1df.png)

So, I guess if there is a problem in PyAV here, it would be in implementation of palettes (or something similar). Perhaps something with [AVSubtitleRect.nb_colors](http://ffmpeg.org/doxygen/trunk/structAVSubtitleRect.html#a7d5855be665def02c2d981a6ac1b7579).

Any chance you can send a small sample to github-pyav-177@mikeboers.com?

**Comment by mikeboers** [comment]
### TODO:

- [ ] Fix the example.
- [ ] Dig further to figure out how the palettes are represented.
- [ ] Implement it (perhaps as a `Palette` class??).

**Comment by alimony** [comment]
Any updates on this issue? Is there anything I can do to help? I'm trying to generate images from bitmap subtitle buffers but I just get black images, but much like you describe, that when run through levels reveal text. There should probably be at least an alpha channel hiding in there somewhere, since these have transparent background when streamed.
